language: java

jdk:
  - oraclejdk8

install:
  - git clone https://github.com/ia-toki/judgels-play-commons.git ../judgels-play-commons
  - git clone https://github.com/ia-toki/judgels-gabriel-commons.git ../judgels-gabriel-commons

script:
  - ./activator test
