language: java

jdk:
  - oraclejdk8

install:
  - git clone https://github.com/judgels/commons.git ../commons
  - git clone https://github.com/judgels/playcommons.git ../playcommons
  - git clone https://github.com/judgels/gabrielcommons.git ../gabrielcommons
  - git clone https://github.com/judgels/sealtielcommons.git ../sealtielcommons

script:
  - ./activator test
